version: "3.8"
services:

  database-test:
    image: mysql
    container_name: db_test_alf
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - test_tech_alf

  phpmyadmin:
    image: phpmyadmin
    container_name: admin_test_alf
    depends_on:
      - database-test
    ports:
      - 8200:80
    environment:
      PMA_HOST: database-test
    networks:
      - test_tech_alf

  www:
    build: php
    container_name: base_test_alf
    ports:
      - "8201:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - test_tech_alf

networks:
  test_tech_alf:

    null
volumes:
  db-data: null
